Controllers/InventoryController.cs
using InventoryManagement.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace InventoryManagement.Controllers
{
    [Authorize]
    public class InventoryController : Controller
    {
        //
        // GET: /Inventory/

        ProductDb _db = new ProductDb();

        //public ActionResult Index(string sortOrder, string CurrentSort, int? page)
        public ActionResult Index()
        {

            if (User.IsInRole("AdminWebSite") == true)
            {
                return RedirectToAction("Index", "Client");
            }

            //int pageSize = 10;
            //int pageIndex = 1;
            //pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            //ViewBag.CurrentSort = sortOrder;

            //sortOrder = String.IsNullOrEmpty(sortOrder) ? "Id" : sortOrder;

         //   IPagedList<Product> products = null;

            var username = User.Identity.Name;
            var user = _db.UserProfiles.SingleOrDefault(u => u.UserName.ToLower() == username);
            var clientId = user.ClientId;
            TempData["clientId"] = clientId;


            //switch (sortOrder)
            //{
            //    case "Id":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Id).Where(m=>m.ClientId == clientId).ToPagedList(pageIndex, pageSize);
            //                    //(m => m.Id).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Id).Where(m => m.ClientId == clientId).ToPagedList(pageIndex, pageSize);
            //                    //(m => m.Id).ToPagedList(pageIndex, pageSize);
            //        break;
            //    case "Name":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "Brand":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "Tags":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "WholesalePrice":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "RetailPrice":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "BuyPrice":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "InitialCostPrice":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "Stock":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "Taxable":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "ManageStock":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "KeepSelling":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "PublishOnline":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;

            //    case "OnlineOrdering":
            //        if (sortOrder.Equals(CurrentSort))
            //            products = _db.Products.OrderByDescending
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        else
            //            products = _db.Products.OrderBy
            //                    (m => m.Name).ToPagedList(pageIndex, pageSize);
            //        break;
            //    // Add sorting statements for other columns

            //    case "Default":
            //        products = _db.Products.OrderBy
            //                (m => m.Id).ToPagedList(pageIndex, pageSize);
            //        break;
            //}
            //return View(_db.Products.ToList().Where(m=> m.IsDeleted != true).Where(m => m.SaleableItem == true));
            return View(_db.Products.ToList().Where(m => m.IsDeleted != true));

            
            //return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                product.ClientId = Convert.ToInt32(TempData["clientId"]);
                _db.Products.Add(product);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [HttpGet]
        //[Authorize(Roles = "Admin")]
        public ActionResult Edit(int Id)
        {
            var model = _db.Products.Find(Id);
            //var temp = System.Web.Security.Membership.GetUser().ProviderUserKey;
            //var temp1 = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
            //var currentUserId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
            //var manager = new UserManager<MyUser>(new UserStore<MyUser>(new MyDbContext()));
            //var currentUser = manager.FindById(User.Identity.GetUserId());
            //System.Web.Profile.ProfileBase _userProfile = System.Web.Profile.ProfileBase.Create(User.Identity.Name);
            //var context = new ProductDb();
            //var username = User.Identity.Name;
            //var user = context.UserProfiles.SingleOrDefault(u => u.UserName.ToLower() == username);
            //var clientId = user.ClientId;
            //var temp = _userProfile.GetPropertyValue("ClientId");


            // For testing
            //TempData["ItemId"] = Id;
            //ViewBag.ItemId = Id;
            Session["ItemId"] = Id;

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                @*<div class="float-left">*@
                    <p class="site-title">@Html.ActionLink("Inventory Management Logo", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @*@Html.Partial("_TopBar")*@
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Dashboard", "Index", "Inventory")</li>
                            @*<li>@Html.ActionLink("Inventory", "About", "Home")</li>
                            <li>@Html.ActionLink("Relationship", "Contact", "Home")</li>*@
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    @*<p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>*@
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Views/Shared/_TopBar.cshtml
<li>@Html.ActionLink("Create Product", "Create", "Inventory")</li>
<li>@Html.ActionLink("Import Products", "Index", "Home")</li>
<li>@Html.ActionLink("Export Products", "ExportData", "Inventory")</li>