Models/Order1.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InventoryManagement.Models
{
    public class Order1
    {
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public int SubproductId { get; set; }

        public DateTime OrderDate { get; set; }

        public DateTime OrderDispatchDate { get; set; }

        public DateTime OrderRequestDate { get; set; }

        public DateTime OrderShipmentDate { get; set; }

        public double Rate { get; set; }
        public double TotalPrice { get; set; }

        public int Quantity { get; set; }

    }
}

Controllers/Order1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using InventoryManagement.Models;

namespace InventoryManagement.Controllers
{
    public class Order1Controller : Controller
    {
        //
        // GET: /Order1/

        ProductDb _db = new ProductDb();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult CheckDetail()
        {
           

            var supplier1 = Request.Form["Supplier"].ToString();
            var subproduct1 = Request.Form["SubProduct"].ToString();


       //     var query = _db.Suppliers.Where(c => c.SupplierName == supplier1).Select(c => new { c.Id, c.SupplierName }).SingleOrDefault();



            if (supplier1 != "")
            {
                var query = _db.Suppliers.Where(c => c.SupplierName == supplier1).Select(c => new { c.Id, c.SupplierName });
                TempData["id"] = new SelectList(query.AsEnumerable(), "Id", "SupplierName", 1);
                TempData["check1"] = "S";
                
            }
            else if (subproduct1 != "")
            {
                var query = _db.SubProducts.Where(c => c.Name == subproduct1).Select(c => new { c.Id, c.Name });
                TempData["id"] = new SelectList(query.AsEnumerable(), "Id", "Name", 1);
                TempData["check1"] = "SP";    
            }
            else
            {
                TempData["id"] = "";
                TempData["check1"] = "";
                return View();
            }

            return RedirectToAction("Index", "OrderPlace");

           // return View();

        }


    }
}

Views/Order1/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>
@using (Html.BeginForm("CheckDetail", "Order1"))
{

<fieldset>
    <legend>Select Order Form</legend>
    <ol>
        <li>
            @Html.Label("Supplier")
            @Html.TextBox("Supplier")

        </li>
        <li>
            @Html.Label("SubProduct")
            @Html.TextBox("SubProduct")

        </li>

    </ol>

 
    <input type="submit" value="CheckDetail" style='width:300px' />



    @*@Html.ActionLink("Check Detail", "Check Detail")*@

    @*@Html.ActionLink("Register", "Register") Check Detail
    <input type="submit" value="CheckDetail" onclick="CheckDetail()" />*@


</fieldset>
}